"""
splits.py

Functions for creating and loading dataset splits.

Test split is defined at event level - entire flood events are held out for
final evaluation. Train and val splits are created at tile level by randomly
splitting all non-test tiles, ensuring the val set has the same distribution
as train.
"""
import random
from pathlib import Path
import pandas as pd
from sentinel_flood_mapper import Config

def create_splits(
        config: Config
) -> pd.DataFrame:
    """
    Build a splits DataFrame and save it as CSV.

    Test events are held out entirely at event level. All remaining tiles from
    both datasets are pooled and randomly split into train and val at tile
    level using val_fraction and random_seed from config.

    Args:
        config: Config object containing split settings and output path.

    Returns:
        DataFrame with columns [filepath, split] where filepath is the path
        to each S1 tile relative to the project root.

    Raises:
        FileNotFoundError: If processed data directories do not exist.
    """
    # Set up vars
    paths = config.paths
    test_events = set(config.splits.test_events)
    val_fraction = config.splits.val_fraction
    random_seed = config.splits.random_seed

    # Set up paths
    sen1_s1_dir = paths.processed_dir / "Sen1Floods11" / "S1"
    sen1_label_dir = paths.processed_dir / "Sen1Floods11" / "LabelHand"
    sturm_s1_dir = paths.processed_dir / "STURM" / "S1"
    sturm_label_dir = paths.processed_dir / "STURM" / "Floodmaps"

    # Check that tiles have already been created in preprocessing
    for d in [sen1_s1_dir, sturm_s1_dir]:
        if not d.exists():
            raise FileNotFoundError(
                f"Processed data directory not found: {d}. Run preprocessing "
                f"before creating splits."
            )

    test_pairs = []
    non_test_pairs = []

    # --- Sen1Floods11 tiles ---
    for s1_path in sorted(sen1_s1_dir.glob("*.tif")):
        event_id = s1_path.name.split("_")[0]
        label_path = sen1_label_dir / s1_path.name.replace(
            "_S1Hand.tif", "_LabelHand.tif"
        )
        if not label_path.exists():
            continue

        if event_id in test_events:
            test_pairs.append((str(s1_path), str(label_path)))
        else:
            non_test_pairs.append((str(s1_path), str(label_path)))

    # --- STURM tiles ---
    for s1_path in sorted(sturm_s1_dir.glob("*.tif")):
        event_id = s1_path.name.split("_")[0]
        label_path = sturm_label_dir / s1_path.name
        if not label_path.exists():
            continue

        if event_id in test_events:
            test_pairs.append((str(s1_path), str(label_path)))
        else:
            non_test_pairs.append((str(s1_path), str(label_path)))

    # Create train/val split
    random.seed(random_seed)
    random.shuffle(non_test_pairs)

    n_val = int(len(non_test_pairs) * val_fraction)
    val_pairs = non_test_pairs[:n_val]
    train_pairs = non_test_pairs[n_val:]

    # Build DataFrame
    project_root = paths.processed_dir.parent.parent

    rows = (
        [{"s1_path": Path(s1).relative_to(project_root),
          "label_path": Path(lbl).relative_to(project_root),
          "split": "train"} for s1, lbl in train_pairs] +
        [{"s1_path": Path(s1).relative_to(project_root),
          "label_path": Path(lbl).relative_to(project_root),
          "split": "val"} for s1, lbl in val_pairs] +
        [{"s1_path": Path(s1).relative_to(project_root),
          "label_path": Path(lbl).relative_to(project_root),
          "split": "test"} for s1, lbl in test_pairs]
    )

    df = pd.DataFrame(rows)

    # Ensure output directory exists then save
    output_path = Path(config.paths.splits_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)

    print(f"Splits saved to {output_path}")
    print(df.groupby("split").size().rename("event_count"))

    return df

def build_file_pairs(
        splits_csv: Path,
        split: str,
        project_root: Path
) -> list[tuple[Path, Path]]:
    """
    Load file pairs for a given split from the splits CSV.

    Args:
        splits_csv: Path to the event_splits.csv file generated by create_splits
        split: One of 'train', 'val' or 'test'
        project_root: Parent directory for project

    Returns:
        List of (s1_path, label_path) tuples for the specified split

    Raises:
        ValueError: If split is not one of 'train', 'val', 'test'
        FileNotFoundError: If splits_csv does not exist
    """
    if not Path(splits_csv).exists():
        raise FileNotFoundError(f"Splits CSV not found: {splits_csv}")

    df = pd.read_csv(splits_csv)

    valid_splits = set(df["split"].unique())
    if split not in valid_splits:
        raise ValueError(
            f"split must be one of {valid_splits}, got '{split}'."
        )

    split_df = df[df["split"] == split]
    file_pairs = [
        (project_root / row["s1_path"], project_root / row["label_path"])
        for _, row in split_df.iterrows()
    ]

    if len(file_pairs) == 0:
        raise ValueError(
            f"No file pairs found for split '{split}'. "
            f"Check that preprocessing has been run and events match those in {splits_csv}."
        )

    return file_pairs

